server:
  port: 8083

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  main:
    web-application-type: reactive

eureka:
  client:
    service-url: # eureka 的地址信息
      defaultZone: http://localhost:8079/eureka
  instance:
    prefer-ip-address: true

